# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rasp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rasp.proto',
  package='rasp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nrasp.proto\x12\x04rasp\"\x07\n\x05\x45mpty\"\x17\n\x05State\x12\x0e\n\x06opened\x18\x01 \x01(\x08\x32.\n\x04Rasp\x12&\n\x08GetState\x12\x0b.rasp.Empty\x1a\x0b.rasp.State\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='rasp.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='rasp.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opened', full_name='rasp.State.opened', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'rasp_pb2'
  # @@protoc_insertion_point(class_scope:rasp.Empty)
  })
_sym_db.RegisterMessage(Empty)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'rasp_pb2'
  # @@protoc_insertion_point(class_scope:rasp.State)
  })
_sym_db.RegisterMessage(State)



_RASP = _descriptor.ServiceDescriptor(
  name='Rasp',
  full_name='rasp.Rasp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=54,
  serialized_end=100,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetState',
    full_name='rasp.Rasp.GetState',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RASP)

DESCRIPTOR.services_by_name['Rasp'] = _RASP

# @@protoc_insertion_point(module_scope)
