# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services.sensor_manager_pb2 as sensor__manager__pb2


class SensorManagerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/sensor.SensorManager/Register',
                request_serializer=sensor__manager__pb2.Sensor.SerializeToString,
                response_deserializer=sensor__manager__pb2.Result.FromString,
                )
        self.Get = channel.unary_unary(
                '/sensor.SensorManager/Get',
                request_serializer=sensor__manager__pb2.Sensor.SerializeToString,
                response_deserializer=sensor__manager__pb2.Result.FromString,
                )


class SensorManagerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=sensor__manager__pb2.Sensor.FromString,
                    response_serializer=sensor__manager__pb2.Result.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sensor__manager__pb2.Sensor.FromString,
                    response_serializer=sensor__manager__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor.SensorManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorManager(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor.SensorManager/Register',
            sensor__manager__pb2.Sensor.SerializeToString,
            sensor__manager__pb2.Result.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor.SensorManager/Get',
            sensor__manager__pb2.Sensor.SerializeToString,
            sensor__manager__pb2.Result.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
