# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_manager.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_manager.proto',
  package='sensor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14sensor_manager.proto\x12\x06sensor\"\'\n\x06Sensor\x12\x0f\n\x07room_id\x18\x01 \x01(\x05\x12\x0c\n\x04host\x18\x02 \x01(\t\":\n\x06Result\x12\x1f\n\x07sensors\x18\x01 \x03(\x0b\x32\x0e.sensor.Sensor\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x66\n\rSensorManager\x12,\n\x08Register\x12\x0e.sensor.Sensor\x1a\x0e.sensor.Result\"\x00\x12\'\n\x03Get\x12\x0e.sensor.Sensor\x1a\x0e.sensor.Result\"\x00\x62\x06proto3'
)




_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='sensor.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='sensor.Sensor.room_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='sensor.Sensor.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=71,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='sensor.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='sensor.Result.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='sensor.Result.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=131,
)

_RESULT.fields_by_name['sensors'].message_type = _SENSOR
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'sensor_manager_pb2'
  # @@protoc_insertion_point(class_scope:sensor.Sensor)
  })
_sym_db.RegisterMessage(Sensor)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'sensor_manager_pb2'
  # @@protoc_insertion_point(class_scope:sensor.Result)
  })
_sym_db.RegisterMessage(Result)



_SENSORMANAGER = _descriptor.ServiceDescriptor(
  name='SensorManager',
  full_name='sensor.SensorManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=133,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='sensor.SensorManager.Register',
    index=0,
    containing_service=None,
    input_type=_SENSOR,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='sensor.SensorManager.Get',
    index=1,
    containing_service=None,
    input_type=_SENSOR,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORMANAGER)

DESCRIPTOR.services_by_name['SensorManager'] = _SENSORMANAGER

# @@protoc_insertion_point(module_scope)
